export const UPDATE_DIRECTION = 'UPDATE_DIRECTION';
export const UPDATE_SCREEN_LOADING_STATUS = 'UPDATE_SCREEN_LOADING_STATUS';

// repair
export const SAVE_REPAIR_PAGE = 'SAVE_REPAIR_PAGE';
export const CLEAR_REPAIR_PAGE = 'CLEAR_REPAIR_PAGE';
export const SAVE_STATUS_LIST = 'SAVE_STATUS_LIST';
